name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Changed Repository
        uses: actions/checkout@master
      - name: Setup Enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Install Packages
        run: composer install --no-dev

      - name: autoload
        run: composer dump-autoload

      - name: Clear route
        run: php artisan route:clear

      - name: Clear Cache
        run: php artisan cache:clear

      - name: Clear View
        run: php artisan view:clear

      - name: Clear Config
        run: php artisan config:clear

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: "65002"
          key: ${{ secrets.PRIVATE_KEY }}
          script: "cd /home/u374771430/domains/bt-sms.com.ng/public_html/adonis && ./deploy.sh"
